# Generated by Django 2.1.1 on 2018-09-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180919_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='FIELDNAME',
            new_name='image',
        ),
    ]
